<?php
function cc_formatters_field_formatter_info() {
  return array(
    'image_content_ref' => array(
      'label' => t('Image Content Reference'),
      'description' => t('Output of a field referencing to Image content type node.'),
      'field types' => array('node_reference'),
    ),
    'addressfield_city_only' => array(
      'label' => t('City only'),
      'description' => t('Output just the city, state and country part of an address field as a single line of comma-separated text.'),
      'field types' => array('addressfield'),
    ),
  );
}
function cc_formatters_field_formatter_view($entity_type, $entity, $field, $instance, $langcode, $items, $display) {
  module_load_include('inc', 'cc_formatters', 'cc_formatters');
  if($display['type'] == 'image_content_ref') {
    $galleries = array();
    drupal_add_js(drupal_get_path('module', 'cc_formatters') . '/cc_formatters.js', 'file');
    foreach($items as $delta => $item) {
      $galleries = array_merge($galleries, _cc_formatters_shadowbox_gallery(node_load($item['nid'])));
    }
    return $galleries;
  }
  else if ($display['type'] == 'addressfield_city_only') {
    $e = array();
    foreach($items as $delta => $item) {
      $c = isset($item['sub_administrative_area']) ? $item['sub_administrative_area'] : NULL;
      $item['sub_administrative_area'] = (!empty($c) && empty($item['locality'])) ? t('@county County', array('@county' => $c)) : NULL;
      $r = isset($item['administrative_area']) ? $item['administrative_area'] : NULL;
      $c = isset($item['country']) ? $item['country'] : NULL;
      $item['administrative_area'] = !in_array($c, array('US', 'CA')) ? _cc_awe_region($r, $c) : $r;
      $a = array_filter($item);
      $e[$delta]['#markup'] = implode(', ', $a);
    }
  return $e;
/*    $element = array();
    $includes = array('dependent_locality', 'locality', 'sub_administrative_area', 'administrative_area', 'country');
    foreach ($items as $delta => $item) {
      $pieces = array();
      foreach ($includes as $include) {
        if (!empty($item[$include])) {
          if ($include == 'sub_administrative_area') {
            $pieces[] = t("@county County", array('@county' => $item[$include]));
          }
          else if (
            $include == 'administrative_area'
            && !in_array($item['country'], array('US', 'CA'))
          ) {
            $pieces[] = _cc_awe_region($item[$include], $item['country']);
          }
          else {
            $pieces[] = $item[$include];
          }
        }
      }
      $element[$delta]['#markup'] = implode(', ', $pieces);
      return $element;
    }*/
  }
}
