<?php
/**
 * @file
 * cc_contexts.features.field.inc
 */

/**
 * Implementation of hook_field_default_fields().
 */
function cc_contexts_field_default_fields() {
  $fields = array();

  // Exported field: 'node-interaction-field_interaction_project'
  $fields['node-interaction-field_interaction_project'] = array(
    'field_config' => array(
      'active' => '1',
      'cardinality' => '1',
      'deleted' => '0',
      'entity_types' => array(),
      'field_name' => 'field_interaction_project',
      'foreign keys' => array(
        'nid' => array(
          'columns' => array(
            'nid' => 'nid',
          ),
          'table' => 'node',
        ),
      ),
      'indexes' => array(
        'nid' => array(
          0 => 'nid',
        ),
      ),
      'module' => 'node_reference',
      'settings' => array(
        'referenceable_types' => array(
          'application' => 0,
          'application_release' => 0,
          'article' => 0,
          'image' => 0,
          'interaction' => 0,
          'organization' => 0,
          'page' => 0,
          'project' => 'project',
          'video' => 0,
        ),
        'view' => array(
          'args' => array(),
          'display_name' => '',
          'view_name' => '',
        ),
      ),
      'translatable' => '0',
      'type' => 'node_reference',
    ),
    'field_instance' => array(
      'bundle' => 'interaction',
      'default_value' => NULL,
      'deleted' => '0',
      'description' => '',
      'display' => array(
        'cc_business_card' => array(
          'label' => 'above',
          'settings' => array(),
          'type' => 'hidden',
          'weight' => 0,
        ),
        'default' => array(
          'label' => 'inline',
          'settings' => array(),
          'type' => 'hidden',
          'weight' => '4',
        ),
        'teaser' => array(
          'label' => 'above',
          'settings' => array(),
          'type' => 'hidden',
          'weight' => 0,
        ),
      ),
      'entity_type' => 'node',
      'field_name' => 'field_interaction_project',
      'label' => 'This field doesn\'t work yet. skip it. Sorry it\'s here. ',
      'required' => 0,
      'settings' => array(
        'user_register_form' => FALSE,
      ),
      'widget' => array(
        'active' => 1,
        'module' => 'node_reference',
        'settings' => array(
          'autocomplete_match' => 'contains',
          'autocomplete_path' => 'node_reference/autocomplete',
          'references_dialog_add' => 0,
          'references_dialog_edit' => 0,
          'references_dialog_search' => 0,
          'references_dialog_search_view' => '',
          'size' => '1',
        ),
        'type' => 'node_reference_autocomplete',
        'weight' => '6',
      ),
    ),
  );

  // Translatables
  // Included for use with string extractors like potx.
  t('This field doesn\'t work yet. skip it. Sorry it\'s here. ');

  return $fields;
}
