<?php

//We have plugin here.
function cc_awe_ctools_plugin_directory($module, $plugin) {
  if ($module == 'addressfield') {
    return $plugin;
  }
}

//Region name.
//$fip - our special region code.
//$iso - country code (ISO standard).
function _cc_awe_region($fip, $iso) {
  return _cc_awe_unquote(db_select('regions')
    ->fields('regions', array('name'))
    ->condition('fip', $fip, '=')
    ->condition('iso', $iso, '=')
    ->execute()
    ->fetchField(0));
}

//No double quotes!
function _cc_awe_unquote($string) {
  return trim($string, '"');
}

//Is not options list separator (double dash).
function _cc_awe_is_not_separator($string) {
  return $string != '--';
}

//Keyed array of regions in a country.
function _cc_awe_regions($country) {
  return array_map('_cc_awe_unquote', db_select('regions')
    ->fields('regions', array('fip', 'name'))
    ->condition('iso', $country, '=')
    ->execute()
    ->fetchAllKeyed(0));
}
