<?php
// $Id: cc_helper.module,v 0.1 2011/09/21 Paul de Paula Exp $

/*
 * Count a view results. $view - unexecuted view object.
 */
function _cc_helper_view_count($view, $display, $custom_arguments = array()) {
	if(!empty($custom_arguments)) {
		$view->args = $custom_arguments;
	}
	$view->set_display($display);
	$view->render();
	if(!empty($view->total_rows)) {
		return $view->total_rows;
	}else{
		if(is_array($view->result)) {
			return count($view->result);
		}
	}
	return FALSE;
}

/*
 * "Using / Sharing" HTML.
 */
function _cc_helper_using_sharing($using = 0, $sharing = 0) {
	$o = '';
	$o .= $using ? '<div class="cc-org-apps"><div class="cc-org-prefix-using">Using</div><div class="cc-org-count">' . $using . '</div><div class="cc-org-postfix">apps</div></div>' : '';
	$o .= $sharing ? '<div class="cc-org-apps"><div class="cc-org-prefix-sharing">Sharing</div><div class="cc-org-count">' . $sharing . '</div><div class="cc-org-postfix">apps</div></div>' : '';
	return $o;
}

/*
 * implementats of hook_user_view_alter
 */
function cc_helper_user_view_alter(&$build) {
  global $user;

  $build['summary']['login_history'] = array(
        '#type' => 'user_profile_item', 
        '#title' => t('Number of logins'), 
        '#markup' => 100, 
        '#weight' => 10,);
  unset($build['summary']);
  drupal_set_title(t(''));
  $userfields = array('field_my_website',
      'field_interests',
      'field_gender', 
      'field_other_social_network',
      'field_share_profile',
      'field_share_address',
      'field_allow_others',
      'field_full_name');
      
  foreach($userfields as $field)
  {
    unset($build[$field]);
  }
}

/* Helper stats functions */
function _cc_helper_get_references_count($nid, $ref_content_type = 'interaction', $ref_field = 'field_interaction_application') {
	$query = new EntityFieldQuery();
	$entities = $query->entityCondition('entity_type', 'node')
						->entityCondition('bundle', $ref_content_type)
						->fieldCondition($ref_field, 'nid', $nid)
						->fieldCondition('field_interaction_type', 'tid', 156)
						->propertyCondition('status', 1)
						->execute();
	
	if($entities){
		return count(node_load_multiple(array_keys($entities['node'])));
	}
	
	
	return FALSE;
}

/* Count unique view results */
function _cc_helper_unique_views_result_count($viewname){
	//$result=0;
	$view = views_get_view($viewname);
	$result_array = array();
	if($view){
		$view->preview();
		$result = $view->result;
		foreach($result as $row){
			$result_array[] = $row->_field_data['node_field_data_field_interaction_organization_nid']['entity']->field_organization_address['und'][0]['locality'];
		}
		$result_array = array_unique($result_array);
		//dsm($result_array);
		return count($result_array);
	}
	return 0;
	
}
