<?php
/**
 * @file
 * Main module file for the CC Actions module.
 * 
 * This module is aimed at providing a focused
 * block (or interface) for users in order to take
 * contextual action, such as editing a node.
 */

/**
 * Implements hook_help().
 */
function cc_actions_help($path, $arg) {
  switch ($path) {
    // Main module help for the CC API module
    case 'admin/help#cc_actions':
      return '<p>' . t('The CC Actions module is aimed at providing a focused block (or interface) for users in order to take contextual action, such as editing a node.') . '</p>';
  
  }
}