<?php
/**
 * @file
 * The main module file for CC Interactions.
 *
 * This module aims to make the creation of Interactions,
 * a content type that ties together Apps and Organizations,
 * easier to create from either of the respective content
 * types.
 *
 * Note that the first iteration of this may be
 * pretty hackish.  Apologies up front.
 */

/**
 * Implements hook_block_info().
 */
function cc_interactions_block_info($delta) {
  $blocks['cc_interactions_apps'] = array(
    'info' => t('Interactions for Apps'),
  );

  return $blocks;
}

/**
 * Implements hook_block_view().
 */
function cc_interactions_block_view($delta) {
  $block = array();

  switch ($delta) {
    case 'cc_interactions_apps':
      $block['subject'] = t('Interactions');
      $block['content'] = cc_interactions_apps_block();
      break;
  }
  return $block;
}

/**
 * Interactions for Apps Block content
 *
 * This should be a theme function.
 */
function cc_interactions_apps_block() {
  $output = '';

  // Ensure we are on a node type Application and get information.
  $node = menu_get_object();
  if (is_object($node) && $node->type == 'application') {
    // List off available interactions types.  We will need
    // field options, the user object with organizations.
    $field = field_info_field('field_interaction_type');
    $values = taxonomy_allowed_values($field);
    
    // Create list
    $items = array();
    foreach ($values as $tid => $action) {
      $items[] = l(t('I <strong>@action</strong> @title', array(
        '@action' => $action,
        '@title' => $node->title,
      )), '<front>', array('html' => TRUE));
    }
    $output .= theme('item_list', array(
      'items' => $items,
    ));
  }
  
  return $output;
}